services:
  postgres:
    image: postgres:14.3-alpine3.16
    container_name: db
    environment:
      POSTGRES_DB: fee_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - app

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_DEFAULT_FEE_FRACTION: 0.01
      DATABASE_URL: db
      REDIS_URL: cache
    depends_on:
      - postgres
      - redis
    networks:
      - app

networks:
  app:
    driver: bridge
