spring:
  application:
    name: bilderlings
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/fee_service_db
    username: admin
    password: password
  liquibase:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/fee_service_db
    user: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: 6379

application:
  fees:
    default_fraction: ${APP_DEFAULT_FEE_FRACTION:0.01}
